import { Card, Heading, List, Stack, Text } from '@chakra-ui/react';
import Head from 'next/head';
import CustomBreadcrumb from '@/components/custom/CustomBreadcrumb';

export default function CookiesPolicy() {
  return (
    <>
      <Head>
        <title>Cookies Policy</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Stack gap={4} p={4}>
        <CustomBreadcrumb
          data={{
            root: 'home',
            first: 'cookies-policy',
          }}
        />
        <Heading size='3xl' color='#0030FF'>
          SM Markets Cookies Policy
        </Heading>
        <Card.Root>
          <Card.Body>
            <Stack spacing={8}>
              {/* Intro */}
              <Text fontSize='md' color='gray.600'>
                To make this site work properly, we sometimes place small data
                files called cookies on your device. Most big websites do this
                too.
              </Text>

              {/* Section: What are cookies */}
              <Stack spacing={3}>
                <Heading as='h2' size='md' color='blue.600'>
                  What are Cookies?
                </Heading>
                <Text fontSize='md' color='gray.700'>
                  A cookie is a small text file that a website saves on your
                  computer or mobile device when you visit the site. It enables
                  the website to remember your actions and preferences (such as
                  login, language, font size and other display preferences) over
                  a period of time, so you don’t have to keep re-entering them
                  whenever you come back to the site or browse from one page to
                  another.
                </Text>
              </Stack>

              {/* Section: How we use cookies */}
              <Stack spacing={3}>
                <Heading as='h2' size='md' color='blue.600'>
                  How do we use our Cookies?
                </Heading>
                <Text>A number of our pages use cookies to remember:</Text>
                <List.Root spacing={2} pl={6} styleType='disc'>
                  <List.Item>
                    your display preferences, such as contrast colour settings
                    or font size
                  </List.Item>
                  <List.Item>
                    if you have already replied to a survey pop-up that asks you
                    if the content was helpful or not (so you won&apos;t be
                    asked again)
                  </List.Item>
                  <List.Item>
                    if you have agreed (or not) to our use of cookies on this
                    site
                  </List.Item>
                </List.Root>
                <Text>
                  Also, some videos embedded in our pages use a cookie to
                  anonymously gather statistics on how you got there and what
                  videos you visited.
                </Text>
                <Text>
                  Enabling these cookies is not strictly necessary for the
                  website to work but it will provide you with a better browsing
                  experience. You can delete or block these cookies, but if you
                  do that some features of this site may not work as intended.
                </Text>
                <Text>
                  The cookie-related information is not used to identify you
                  personally and the pattern data is fully under our control.
                  These cookies are not used for any purpose other than those
                  described here.
                </Text>
              </Stack>

              {/* Section: Control cookies */}
              <Stack spacing={3}>
                <Heading as='h2' size='md' color='blue.600'>
                  How to control Cookies?
                </Heading>
                <Text>
                  You can control and/or delete cookies as you wish – for
                  details, see{' '}
                  <Text
                    as='a'
                    href='https://aboutcookies.org'
                    color='blue.500'
                    target='_blank'
                    rel='noopener noreferrer'
                  >
                    aboutcookies.org
                  </Text>
                  . You can delete all cookies that are already on your computer
                  and you can set most browsers to prevent them from being
                  placed. If you do this, however, you may have to manually
                  adjust some preferences every time you visit a site and some
                  services and functionalities may not work.
                </Text>
              </Stack>
            </Stack>
          </Card.Body>
        </Card.Root>
      </Stack>
    </>
  );
}
