// components/Layout.js

import { Heading, Stack } from '@chakra-ui/react';
import Head from 'next/head';
import CustomBreadcrumb from '@/components/custom/CustomBreadcrumb';

export default function MyAccount() {
  return (
    <>
      <Head>
        <title>My Account</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Stack gap={4} p={4}>
        <CustomBreadcrumb
          data={{
            root: 'home',
            first: 'my-account',
          }}
        />
        <Heading>My Account</Heading>
      </Stack>
    </>
  );
}
