import {
  Button,
  Card,
  Field,
  Heading,
  Input,
  NativeSelect,
  SimpleGrid,
  Stack,
} from '@chakra-ui/react';
import Head from 'next/head';
import { useState } from 'react';
import CustomBreadcrumb from '@/components/custom/CustomBreadcrumb';
import { supabase } from '@/helper/supabase';

export default function Signup() {
  const [form, setForm] = useState({
    email: '',
    password: '',
    confirmPassword: '',
    firstname: '',
    lastname: '',
    phone: '',
    dob: '',
    gender: 'male',
  });
  const [loading, setLoading] = useState(false);

  const handleChange = (e) =>
    setForm({ ...form, [e.target.name]: e.target.value });

  const handleSignup = async () => {
    if (form.password !== form.confirmPassword) {
      alert('Passwords do not match.');
      return;
    }

    setLoading(true);

    const { data, error } = await supabase.auth.signUp({
      email: form.email,
      password: form.password,
      options: {
        data: {
          // firstname: form.firstname,
          // lastname: form.lastname,
          display_name: `${form.firstname} ${form.lastname}`, // 👈 auto combine
          phone: form.phone,
          // dob: form.dob,
          // gender: form.gender,
        },
      },
    });

    setLoading(false);
    if (error) {
      alert(error.message);
    } else {
      alert('Signup successful! Please check your email for verification.');
      const { error: profileError } = await supabase.from('users').insert([
        {
          id: data.user.id, // use same UUID from auth
          first_name: form.firstname,
          last_name: form.lastname,
          gender: form.gender,
          email: form.email,
          phone: form.phone,
          dob: form.dob,
          shipping_address: null, // optional: can update later
          cart_item: [], // start empty
        },
      ]);

      if (profileError) throw profileError;
      setForm({
        email: '',
        password: '',
        confirmPassword: '',
        firstname: '',
        lastname: '',
        phone: '',
        dob: '',
        gender: '',
      });
    }
  };

  return (
    <>
      <Head>
        <title>Signup | SM Market Mapua</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Stack gap={4} p={4}>
        <CustomBreadcrumb
          data={{
            root: 'home',
            first: 'login',
          }}
        />
        <Heading size='3xl' color='#0030FF'>
          Welcome Back!
        </Heading>
        <SimpleGrid columns={{ base: 1, md: 2 }} gap={6}>
          {/* CARD 1 — LOGIN DETAILS */}
          <Card.Root>
            <Card.Body>
              <Stack gap={4}>
                <Field.Root>
                  <Field.Label>Email</Field.Label>
                  <Input
                    name='email'
                    type='email'
                    placeholder='you@example.com'
                    value={form.email}
                    onChange={handleChange}
                    required
                  />
                </Field.Root>

                <Field.Root>
                  <Field.Label>Password</Field.Label>
                  <Input
                    name='password'
                    type='password'
                    placeholder='••••••••'
                    value={form.password}
                    onChange={handleChange}
                    required
                  />
                </Field.Root>

                <Field.Root>
                  <Field.Label>Retype Password</Field.Label>
                  <Input
                    name='confirmPassword'
                    type='password'
                    placeholder='••••••••'
                    value={form.confirmPassword}
                    onChange={handleChange}
                    required
                  />
                </Field.Root>
              </Stack>
            </Card.Body>
          </Card.Root>

          {/* CARD 2 — PERSONAL DETAILS */}
          <Card.Root>
            <Card.Body>
              <Stack gap={4}>
                <Field.Root>
                  <Field.Label>First Name</Field.Label>
                  <Input
                    name='firstname'
                    placeholder='John'
                    value={form.firstname}
                    onChange={handleChange}
                  />
                </Field.Root>

                <Field.Root>
                  <Field.Label>Last Name</Field.Label>
                  <Input
                    name='lastname'
                    placeholder='Doe'
                    value={form.lastname}
                    onChange={handleChange}
                  />
                </Field.Root>

                <Field.Root>
                  <Field.Label>Phone Number</Field.Label>
                  <Input
                    name='phone'
                    type='tel'
                    placeholder='+63 900 000 0000'
                    value={form.phone}
                    onChange={handleChange}
                  />
                </Field.Root>

                <Field.Root>
                  <Field.Label>Date of Birth</Field.Label>
                  <Input
                    name='dob'
                    type='date'
                    value={form.dob}
                    onChange={handleChange}
                  />
                </Field.Root>

                <Field.Root>
                  <Field.Label>Gender</Field.Label>
                  <NativeSelect.Root
                    name='gender'
                    placeholder='Select gender'
                    value={form.gender}
                    onChange={handleChange}
                  >
                    <NativeSelect.Field>
                      <option value='male'>Male</option>
                      <option value='female'>Female</option>
                      <option value='other'>Other</option>
                    </NativeSelect.Field>
                  </NativeSelect.Root>
                </Field.Root>

                <Button
                  colorPalette='blue'
                  size='xl'
                  loading={loading}
                  onClick={handleSignup}
                >
                  Sign Up
                </Button>
              </Stack>
            </Card.Body>
          </Card.Root>
        </SimpleGrid>
      </Stack>
    </>
  );
}
